const SLUG_SUFFIX_LENGTH = 5;
const MAX_TITLE_LENGTH = 50;

/**
 * Generates a preview slug from title with deterministic suffix.
 * Format: <slugified-title>-<5-char-alphanumeric>
 *
 * Note: This is a preview only. The actual slug is generated by the backend
 * with a random suffix. This preview uses a deterministic suffix based on the
 * title to maintain consistency while typing.
 *
 * @param title - The title to generate slug from
 * @returns Preview slug string
 */
export function generateSlugPreview(title: string): string {
	const base = slugifyTitle(title);
	const suffix = generateDeterministicSuffix(title);
	return base ? `${base}-${suffix}` : suffix;
}

/**
 * Converts title to URL-safe slug base.
 * - Lowercase, remove accents, keep alphanumeric and hyphens
 * - Collapse multiple hyphens, trim edges, max 50 chars
 */
function slugifyTitle(title: string): string {
	if (!title) return '';

	return title
		.toLowerCase()
		.normalize('NFD')
		.replace(/[\u0300-\u036f]/g, '') // Remove accents
		.replace(/[^a-z0-9\s-]/g, '') // Keep alphanumeric, spaces, hyphens
		.replace(/[\s_]+/g, '-') // Spaces/underscores → hyphen
		.replace(/-+/g, '-') // Collapse multiple hyphens
		.replace(/^-|-$/g, '') // Trim edge hyphens
		.slice(0, MAX_TITLE_LENGTH);
}

/**
 * Generates a deterministic 5-char lowercase alphanumeric suffix.
 * Uses a simple hash of the title to create a consistent suffix for preview.
 *
 * The actual backend uses randomBytes, but for preview we want consistency.
 */
function generateDeterministicSuffix(title: string): string {
	const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';

	// Simple hash function for deterministic suffix
	let hash = 0;
	for (let i = 0; i < title.length; i++) {
		const char = title.charCodeAt(i);
		hash = (hash << 5) - hash + char;
		hash = hash & hash; // Convert to 32-bit integer
	}

	// Generate 5 characters from hash
	let result = '';
	for (let i = 0; i < SLUG_SUFFIX_LENGTH; i++) {
		// Use absolute value and modulo to get index
		const index = Math.abs(hash + i * 31) % chars.length;
		result += chars[index];
	}

	return result;
}
