const SLUG_SUFFIX_LENGTH = 5;
const MAX_TITLE_LENGTH = 50;

// Hoisted RegExp — avoid re-creation on every call
const RE_ACCENTS = /[\u0300-\u036f]/g;
const RE_NON_ALPHANUMERIC = /[^a-z0-9\s-]/g;
const RE_SPACES_UNDERSCORES = /[\s_]+/g;
const RE_MULTIPLE_HYPHENS = /-+/g;
const RE_EDGE_HYPHENS = /^-|-$/g;

/**
 * Generates a preview slug from title with deterministic suffix.
 * Format: <slugified-title>-<5-char-alphanumeric>
 *
 * Note: This is a preview only. The actual slug is generated by the backend
 * with a random suffix. This preview uses a deterministic suffix based on the
 * title to maintain consistency while typing.
 *
 * @param title - The title to generate slug from
 * @returns Preview slug string
 */
export function generateSlugPreview(title: string): string {
	const base = slugifyTitle(title);
	const suffix = generateDeterministicSuffix(title);
	return base ? `${base}-${suffix}` : suffix;
}

/**
 * Converts title to URL-safe slug base.
 * - Lowercase, remove accents, keep alphanumeric and hyphens
 * - Collapse multiple hyphens, trim edges, max 50 chars
 */
function slugifyTitle(title: string): string {
	if (!title) return '';

	return title
		.toLowerCase()
		.normalize('NFD')
		.replace(RE_ACCENTS, '') // Remove accents
		.replace(RE_NON_ALPHANUMERIC, '') // Keep alphanumeric, spaces, hyphens
		.replace(RE_SPACES_UNDERSCORES, '-') // Spaces/underscores → hyphen
		.replace(RE_MULTIPLE_HYPHENS, '-') // Collapse multiple hyphens
		.replace(RE_EDGE_HYPHENS, '') // Trim edge hyphens
		.slice(0, MAX_TITLE_LENGTH);
}

/**
 * Generates a deterministic 5-char lowercase alphanumeric suffix.
 * Uses a simple hash of the title to create a consistent suffix for preview.
 *
 * The actual backend uses randomBytes, but for preview we want consistency.
 *
 * @param title - The title to hash
 * @returns 5-char alphanumeric suffix string
 */
function generateDeterministicSuffix(title: string): string {
	const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';

	// DJB2 variant — (hash << 5) - hash is equivalent to hash * 31.
	// 31 is a Mersenne prime producing good distribution for short strings.
	let hash = 0;
	for (let i = 0; i < title.length; i++) {
		const charCode = title.charCodeAt(i);
		hash = (hash << 5) - hash + charCode;
		hash = hash & hash; // Clamp to 32-bit integer
	}

	// Spread hash across SLUG_SUFFIX_LENGTH positions using prime stride (31)
	// to avoid clustering when hash values are close.
	let suffix = '';
	for (let i = 0; i < SLUG_SUFFIX_LENGTH; i++) {
		const index = Math.abs(hash + i * 31) % chars.length;
		suffix += chars[index];
	}

	return suffix;
}
