'use client';

import { CheckCircle2, HelpCircle, Lock, XCircle } from 'lucide-react';
import { motion } from 'framer-motion';
import { useInView } from 'framer-motion';
import { useRef } from 'react';

/**
 * ComparisonDiagram Component
 *
 * Side-by-side visual comparison of Traditional vs Provably Fair raffles.
 */
export function ComparisonDiagram() {
	const ref = useRef<HTMLDivElement>(null);
	const isInView = useInView(ref, { once: true, margin: '-50px' });

	return (
		<div ref={ref} className="grid gap-6 md:grid-cols-2">
			{/* Traditional */}
			<motion.div
				initial={{ opacity: 0, x: -20 }}
				animate={isInView ? { opacity: 1, x: 0 } : { opacity: 0, x: -20 }}
				transition={{ duration: 0.5 }}
				className="rounded-xl border-2 border-red-200 bg-red-50 p-6"
			>
				<div className="mb-4 flex items-center gap-2">
					<XCircle className="size-6 text-red-500" />
					<h3 className="text-lg font-semibold text-red-700">Traditional</h3>
				</div>

				{/* Black box visualization */}
				<div className="mb-4 flex justify-center">
					<div className="relative">
						<div className="flex size-24 items-center justify-center rounded-lg bg-neutral-800">
							<div className="grid grid-cols-2 gap-1">
								{[0, 1, 2, 3].map(i => (
									<motion.div
										key={i}
										animate={{ opacity: [0.3, 0.7, 0.3] }}
										transition={{
											duration: 2,
											repeat: Infinity,
											delay: i * 0.3,
										}}
									>
										<HelpCircle className="size-5 text-neutral-400" />
									</motion.div>
								))}
							</div>
						</div>
						<p className="mt-2 text-center text-xs text-neutral-500">
							Black Box
						</p>
					</div>
				</div>

				<ul className="space-y-2 text-sm text-red-800">
					<li className="flex items-start gap-2">
						<XCircle className="mt-0.5 size-4 shrink-0" />
						<span>Results hidden in organizer&apos;s server</span>
					</li>
					<li className="flex items-start gap-2">
						<XCircle className="mt-0.5 size-4 shrink-0" />
						<span>Can add tickets after seeing numbers</span>
					</li>
					<li className="flex items-start gap-2">
						<XCircle className="mt-0.5 size-4 shrink-0" />
						<span>No way to verify fairness</span>
					</li>
				</ul>
			</motion.div>

			{/* Provably Fair */}
			<motion.div
				initial={{ opacity: 0, x: 20 }}
				animate={isInView ? { opacity: 1, x: 0 } : { opacity: 0, x: 20 }}
				transition={{ duration: 0.5, delay: 0.2 }}
				className="rounded-xl border-2 border-green-200 bg-green-50 p-6"
			>
				<div className="mb-4 flex items-center gap-2">
					<CheckCircle2 className="size-6 text-green-500" />
					<h3 className="text-lg font-semibold text-green-700">Provably Fair</h3>
				</div>

				{/* Transparent visualization */}
				<div className="mb-4 flex justify-center">
					<div className="relative">
						<div className="flex size-24 items-center justify-center rounded-lg border-2 border-dashed border-green-300 bg-white">
							<div className="grid grid-cols-2 gap-1">
								{[0, 1, 2, 3].map(i => (
									<motion.div
										key={i}
										initial={{ scale: 0 }}
										animate={isInView ? { scale: 1 } : { scale: 0 }}
										transition={{ delay: 0.5 + i * 0.1 }}
									>
										<CheckCircle2 className="size-5 text-green-500" />
									</motion.div>
								))}
							</div>
						</div>
						<p className="mt-2 text-center text-xs text-neutral-500">
							Transparent
						</p>
					</div>
				</div>

				<ul className="space-y-2 text-sm text-green-800">
					<li className="flex items-start gap-2">
						<Lock className="mt-0.5 size-4 shrink-0" />
						<span>Ticket data locked on blockchain before draw</span>
					</li>
					<li className="flex items-start gap-2">
						<CheckCircle2 className="mt-0.5 size-4 shrink-0" />
						<span>
							Random number generated by an independent third party (Chainlink
							VRF)
						</span>
					</li>
					<li className="flex items-start gap-2">
						<CheckCircle2 className="mt-0.5 size-4 shrink-0" />
						<span>Anyone can verify results</span>
					</li>
				</ul>
			</motion.div>
		</div>
	);
}
